Repository ONSdigital/sdc-global-design-patterns, pull requests merged in 2018-09, with the labels that each got.

#161 Added a .u-nowrap utility class
  assets/sass/partials/utilities/_utilities.scss
Labels: enhancement

#166 Add has-js class to guidance content to fix bug
  components/definition/_definition.scss
  components/guidance/_guidance.scss
Labels: bug

#146 Component status
  components/status/README.md
  components/status/_status.scss
  components/status/status.config.js
  components/status/status.hbs
Labels: WIP
