Repository ONSdigital/sdc-global-design-patterns, pull requests merged in 2018-12, with the labels that each got.

#232 Added temporary fix for month dropdown date input on mobile
  components/02-form-elements/date/date.hbs
  components/02-form-elements/fields/field/_field.scss
Labels: visual defect

#234 Ensure mutually exclusive works with input types other than text
  components/02-form-elements/mutually-exclusive/mutually-exclusive.js
  tests/karma/spec/mutuallyexclusive.spec.js
Labels: bug

#237 Ensure exclusive checkbox value is not cleared
  components/02-form-elements/mutually-exclusive/mutually-exclusive.js
  tests/karma/spec/mutuallyexclusive.spec.js
Labels: bug

#235 Prevent text from being split across pages on iOS when printing
  assets/sass/partials/base/_print.scss
Labels: bug

#238 Select caret does not show in IE11
  assets/img/icons/icons--chevron-down.svg
Labels: visual defect

#196 Component table update
  assets/img/.DS_Store
  assets/img/icons/icons--sort-sprite.svg
  assets/js/components.js
  assets/sass/partials/base/_tables.scss
  components/_preview__full-width.hbs
  components/table/_table.scss
  components/table/readme.md
  components/table/scrollable-table.js
  components/table/sortable-table.js
  components/table/table.config.js
  components/table/table.hbs
  tests/karma/spec/table-scrollable.spec.js
  tests/karma/spec/table-sortable.spec.js
  tests/karma/spec/tabs.spec.js
Labels: A11y testing required, Do not merge, unit tests needed
