Repository ONSdigital/sdc-global-design-patterns, pull requests merged in 2018-07, with the labels that each got.

#119 Defining link colour for skip to content
  components/_preview-skip.hbs
  components/skip/_skip.scss
  components/skip/skip.config.js
  components/skip/skip.hbs
Labels: bug, visual defect

#121 overflow:hidden removed from definition component
  assets/sass/partials/behaviours/_details-toggle.scss
  components/definition/_definition.scss
  components/details/_details.scss
Labels: visual defect

#126 added box-shadow to bridge the highlight offset on skip to content link
  components/skip/_skip.scss
Labels: visual defect

#128 Fix guidance content
  assets/sass/partials/behaviours/_details-toggle.scss
  components/guidance/_guidance.scss
Labels: bug, visual defect

#91 Component pagination
  assets/sass/partials/helpers/_mixins.scss
  components/pagination/README.md
  components/pagination/_pagination.scss
  components/pagination/pagination.config.js
  components/pagination/pagination.hbs
Labels: WIP

#127 Component footer (light)
  assets/img/UKOpenGovernmentLicence-grey.svg
  assets/img/ons-logo-black-cy.svg
  components/footer/README.md
  components/footer/_footer.scss
  components/footer/footer--internal-service.hbs
  components/footer/footer--poweredbyons-transactional-cy.hbs
  components/footer/footer--poweredbyons-transactional.hbs
  components/footer/footer--poweredbyons.hbs
  components/footer/footer--transactional.hbs
  components/footer/footer.config.js
  components/footer/footer.hbs
Labels: enhancement

#139 Documentation on code standards
  README.md
  docs/01-index.config.js
  docs/01-index.md
  docs/08-feedback.md
Labels: enhancement
