Repository ONSdigital/sdc-global-design-patterns, pull requests merged in 2018-11, with the labels that each got.

#203 Add array polyfills
  assets/js/polyfills.js
  package.json
  yarn.lock
Labels: bug

#205 Charater limit text string moved from Javascript to HTML control
  components/02-form-elements/mutually-exclusive/mutually-exclusive--text-area.hbs
  components/02-form-elements/textarea/character-limit.js
  components/02-form-elements/textarea/textarea.config.js
  components/02-form-elements/textarea/textarea.hbs
  components/feedback/feedback.hbs
Labels: Breaking Changes

#213 2593 add lighthouse testing to ci
  assets/sass/patternlib.scss
  lighthouse.js
  package.json
  yarn.lock
Labels: accessibility

#216 Ensure yarn installs fresh dependencies for every build
  .gitignore
  package.json
Labels: enhancement

#211 Automated cross browser testing
  .travis.yml
  assets/js/api/_load.js
  assets/js/api/boot.spec.js
  assets/js/inpagelink.js
  docs/08-feedback.md
  package.json
  tests/karma/karma.conf.browserstack-launchers.js
  tests/karma/karma.conf.js
  tests/karma/karma.conf.local-launchers.js
  tests/karma/spec/inpagelinks.spec.js
  yarn.lock
Labels: Do not merge

#204 2568 input font sizes widths and button sizes
  .eslintrc
  assets/js/components.js
  assets/sass/partials/base/_forms.scss
  assets/sass/partials/base/_global.scss
  assets/sass/partials/helpers/_functions.scss
  assets/sass/partials/vars/_forms.scss
  components/02-form-elements/currency/currency.hbs
  components/02-form-elements/date/README.md
  components/02-form-elements/date/date--range.hbs
  components/02-form-elements/date/date.config.js
  components/02-form-elements/date/date.hbs
  components/02-form-elements/duration/README.md
  components/02-form-elements/duration/duration.config.js
  components/02-form-elements/duration/duration.hbs
  components/02-form-elements/fields/field/_field.scss
  components/02-form-elements/fields/field/field.hbs
  components/02-form-elements/fields/fieldgroup/fieldgroup--date.hbs
  components/02-form-elements/fields/fieldgroup/fieldgroup.config.js
  components/02-form-elements/fields/fieldgroup/fieldgroup.hbs
  components/02-form-elements/input-type/_input-type.scss
  components/02-form-elements/input/_input.scss
  components/02-form-elements/input/input--checkbox-other.hbs
  components/02-form-elements/input/input--checkbox.hbs
  components/02-form-elements/input/input--percentage.hbs
  components/02-form-elements/input/input--radio-other.hbs
  components/02-form-elements/input/input--radio.hbs
  components/02-form-elements/input/input.config.js
  components/02-form-elements/input/input.hbs
  components/02-form-elements/label/_label.scss
  components/02-form-elements/mutually-exclusive/mutually-exclusive--date.hbs
  components/02-form-elements/mutually-exclusive/mutually-exclusive--text-area.hbs
  components/02-form-elements/mutually-exclusive/mutually-exclusive.hbs
  components/02-form-elements/mutually-exclusive/mutually-exclusive.js
  components/02-form-elements/unit/README.md
  components/02-form-elements/unit/unit.hbs
  components/_preview__container.hbs
  components/button/_buttons.scss
  components/tabs/tabs.config.js
  components/tabs/tabs.hbs
  fractal.js
  tests/karma/spec/mutuallyexclusive.spec.js
  tests/karma/spec/tabs.spec.js
Labels: Breaking Changes
